export const appTitle = 'Todolist App'
export const githubLink = 'https://github.com/gz-gary'
export const sourceCodeLink = 'https://github.com/gz-gary/todolist-frontend'
export const blogLink = 'https://zjlwiki.top'
export const apiUrl = 'https://todolis-backend-fsokjcleie.cn-shanghai.fcapp.run/api'